# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NEW(object):
    def setupUi(self, NEW):
        NEW.setObjectName("NEW")
        NEW.setEnabled(True)
        NEW.resize(497, 159)
        NEW.setMinimumSize(QtCore.QSize(354, 159))
        NEW.setMaximumSize(QtCore.QSize(673, 159))
        self.verticalLayout = QtWidgets.QVBoxLayout(NEW)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(NEW)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addressLineEdit = QtWidgets.QLineEdit(NEW)
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.horizontalLayout_4.addWidget(self.addressLineEdit)
        self.toolButton = QtWidgets.QToolButton(NEW)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(NEW)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.subjectLineEdit = QtWidgets.QLineEdit(NEW)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.horizontalLayout_5.addWidget(self.subjectLineEdit)
        self.toolButton_2 = QtWidgets.QToolButton(NEW)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_5.addWidget(self.toolButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tagLineEdit = QtWidgets.QLineEdit(NEW)
        self.tagLineEdit.setObjectName("tagLineEdit")
        self.horizontalLayout_6.addWidget(self.tagLineEdit)
        self.toolButton_3 = QtWidgets.QToolButton(NEW)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_6.addWidget(self.toolButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(NEW)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(NEW)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(NEW)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.horizontalLayout.addWidget(self.nameLineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.OKButton = QtWidgets.QPushButton(NEW)
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_2.addWidget(self.OKButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(NEW)
        QtCore.QMetaObject.connectSlotsByName(NEW)

    def retranslateUi(self, NEW):
        _translate = QtCore.QCoreApplication.translate
        NEW.setWindowTitle(_translate("NEW", "Dialog"))
        self.label_8.setText(_translate("NEW", "Name"))
        self.addressLineEdit.setPlaceholderText(_translate("NEW", "address"))
        self.toolButton.setText(_translate("NEW", "..."))
        self.label_7.setText(_translate("NEW", "Subject"))
        self.subjectLineEdit.setPlaceholderText(_translate("NEW", "subject"))
        self.toolButton_2.setText(_translate("NEW", "..."))
        self.tagLineEdit.setPlaceholderText(_translate("NEW", "tag"))
        self.toolButton_3.setText(_translate("NEW", "..."))
        self.label_5.setText(_translate("NEW", "Tag"))
        self.label_6.setText(_translate("NEW", "Address"))
        self.nameLineEdit.setPlaceholderText(_translate("NEW", "name"))
        self.OKButton.setText(_translate("NEW", "OK"))


